# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:


- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'pguerra-final-job-devsecopsv4'
    scannerMode: 'MSBuild'
    projectKey: 'pguerra-final-job-devsecopsv4_spring-boot-kubernetes'
    projectName: 'spring-boot-kubernetes'

- task: Maven@4
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false

- task: dependency-check-build-task@6
  inputs:
    projectName: 'scan-librerias'
    scanPath: '**/*.java'
    format: 'HTML'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: 'docker-lab'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'docker-lab'
    repository: 'pguerra-final-job-devsecopsv4 / spring-boot-kubernetes'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'