#pool:
#  vmImage: ubuntu-latest
#steps:
#STAGE SAST
trigger:
- main

pool: 
 vmImage: ubuntu-latest

stages:
- stage: SAST 
  jobs:
  - job: SAST
    displayName: 'SAST'
    steps: 
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sonarcloud'
        organization: 'pguerra-final-job-devsecopsv4'
        scannerMode: 'MSBuild'
        projectKey: 'pguerra-final-job-devsecopsv4_spring-boot-kubernetes'
        projectName: 'spring-boot-kubernetes'