#pool:
#  vmImage: ubuntu-latest
#steps:
#STAGE SAST
trigger:
- main



pool:
   vmImage: ubuntu-latest

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'pguerra-final-job-devsecopsv4'
    scannerMode: 'MSBuild'
    projectKey: 'pguerra-final-job-devsecopsv4_spring-boot-kubernetes'
    projectName: 'spring-boot-kubernetes'


- task: Maven@4
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false

#STAGE SCA

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.pdf'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false



- task: dependency-check-build-task@6
  inputs:
    projectName: 'scan-librerias'
    scanPath: '**/*.java'
    format: 'HTML'


# STAGE Container Securiyty

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.pdf'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false


- task: DockerInstaller@
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'pguerra-final-job-devsecopsv4/spring-boot-kubernetes'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- script: |
    sudo apt-get install -y rpm
    wget https://github.com/aquasecurity/trivy/releases/download/v0.27.1/trivy_0.27.1_Linux-64bit.deb
    sudo dpkg -i trivy_0.27.1_Linux-64bit.deb
    trivy image pguerra-final-job-devsecopsv4/spring-boot-kubernetes:latest
  displayName: Image Scan

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'pguerra-final-job-devsecopsv4/spring-boot-kubernetes/spring-boot-kubernetes'
    command: 'push'
    tags: 'latest'